name: NG2 Configuration Example
machine_name: ng2-example-configuration
type: pdb
description: 'NG 2 Example Component Configuration'
package: NG2
# version: '1.0.0'
# core: '8.x'
module_status: active
presentation: ng2
configuration:
  text:
    type: textfield
    title: 'What do you want to say?'
    default_value: 'Hello world!'

# Information added by Drupal.org packaging script on 2016-11-17
version: '8.x-1.0-alpha6'
core: '8.x'
project: 'pdb'
datestamp: 1479397524
